(() => {
 'use strict';
 const $=s=>document.querySelector(s),money=n=>'$'+n.toLocaleString('en-US');
 const rows=items=>'<div class="rows">'+items.map(([a,b])=>`<div class="row"><span>${a}</span><strong>${b}</strong></div>`).join('')+'</div>';
 const dates=s=>`<div class="dates">${s}</div>`;
 const note=s=>`<p class="note">${s}</p>`;
 const chapters=[
 {title:'Nexus Terminal',phase:'A BUILDING, ITS COST AND ITS PROGRAMME',intro:'A visual explanation of the Porto metro-station study: what must be built, how it is estimated, and when the work takes place.',level:7,html:`<div class="metric">$60,082,987<small>Reported study estimate</small></div>`+rows([['Programme','530 schedule days'],['Gross built-up area','260,000 sq. ft.'],['Activities / critical activities','Approx. 300 / 100']])+note('Use Next chapter or the slider. Drag the model to rotate it. Pan and zoom to inspect the construction.'),source:'Portfolio pp. 6, 8–10. Study parameters, not delivered-project results.'},
 {title:'The estimate before construction',phase:'ESTIMATE / SCOPE AND QUANTITIES',intro:'The study develops an area-based conceptual estimate into a drawing-based baseline, using Bluebeam quantities, RSMeans rates and CSI trade divisions.',level:7,html:rows([['Direct cost, reported',money(46248039)],['Indirect cost, reported',money(13834949)],['Total project cost, reported',money(60082987)]])+note('Example from the estimate: structural steel framing, 726 tons × $2,200/ton = $1,597,200. Model geometry helps identify scope. Drawing takeoffs establish quantities.')+note('The reported direct and indirect subtotals differ from the reported total by $1. The source also contains an existing-conditions chart/table discrepancy. See Source notes.'),source:'Portfolio p. 8. Estimate allowances do not represent expenditure over time.'},
 {title:'Design and procurement',phase:'01 / BEFORE SITE WORK',intro:'Resolve the design and purchasing decisions before the physical sequence begins. The imported curtain wall is a stated procurement risk.',level:0,html:dates('Design: 30 Jan–24 Mar 2026')+rows([['Estimation','25 Mar–17 Apr 2026'],['Bidding','20 Apr–05 Jun 2026'],['Submittals','05 Jun–27 Jul 2026'],['Logistics / procurement','12 Jun–03 Aug 2026']])+note('A simplified wireframe defines the scope. Approved drawings, quantities and material submittals provide the basis for the build.'),source:'Portfolio p. 9. Dates follow visible summary rows. Procurement and early construction overlap.'},
 {title:'Groundwork and foundations',phase:'02 / BELOW GROUND',intro:'Prepare access and utilities, excavate, bore piles, place reinforcement and cast the foundation. The model reveals the below-ground structure.',level:1,html:dates('Site preparation: 06 Jul–20 Aug 2026<br>Foundation: 21 Aug 2026–05 Feb 2027')+rows([['Earthwork allowance',money(401930)],['Concrete trade allowance',money(4464080)]])+note('Concrete is a whole-project trade allowance, not the foundation cost alone. The portfolio lists excavation and foundation weather risk. Location-specific weather assumptions require validation.'),source:'Portfolio pp. 8–9. Pile layout and excavation geometry are illustrative.'},
 {title:'The concrete frame rises',phase:'03 / STRUCTURE',intro:'Repeat the structural cycle: columns and core, beams, deck reinforcement, concrete placement and curing. Release each level only after its structural requirements are met.',level:3,html:dates('Superstructure: 08 Feb–30 Jul 2027')+rows([['Concrete allowance',money(4464080)],['Metals allowance',money(1597200)]])+note('The schedule lists core work, floor slabs, steel decking and beams by level. The model highlights these assemblies as a coherent frame.')+note('The full metals allowance also covers later roof steel. Neither trade allowance is added again as a new phase cost.'),source:'Portfolio pp. 8–10. The animation groups activity rows into teaching stages.'},
 {title:'Roof and enclosure',phase:'04 / WEATHER ENCLOSURE',intro:'Erect the roof structure and close the envelope. Coordinate roofing and curtain-wall deliveries with the frame so interior areas can become weather-protected.',level:4,html:dates('Roof: 01–30 Jul 2027<br>Façade / exterior finishes: 15 Mar–18 Aug 2027')+rows([['Thermal / moisture protection',money(1830812)],['Openings, reported',money(55690)]])+note('Façade work overlaps structure in the source. This chapter isolates it visually for clarity. The openings allowance is reported as written and should not be treated as a validated curtain-wall budget.'),source:'Portfolio pp. 8, 10. Source dates overlap; chapter order is not a serial Gantt programme.'},
 {title:'Services within the frame',phase:'05 / BUILDING SYSTEMS',intro:'Install the service routes while access remains available. The cutaway shows indicative ducts and pipe runs beneath the decks.',level:5,html:dates('MEP summary: 17 May–25 Sep 2027')+rows([['HVAC',money(2181700)],['Plumbing',money(1353300)],['Electrical',money(751150)],['Fire suppression',money(259530)]])+note('Coordinate openings, clearances and access before closing ceilings. Coloured service routes are illustrative and do not reproduce the original coordinated BIM model.'),source:'Portfolio pp. 8, 10. Trade totals are estimate allowances, not a monthly cash-flow forecast.'},
 {title:'Interiors and final fixtures',phase:'06 / FINISHES',intro:'Complete partitions, ceilings, floors, equipment and final fixtures as zones become ready. Finishes form the largest single trade allowance in the displayed estimate.',level:6,html:dates('Interior finishes: 15 Mar–06 Dec 2027')+`<div class="metric">$15,305,796<small>Finishes allowance in the portfolio estimate</small></div><div class="bar"><i style="width:33.1%"></i></div>`+note('Approximately 33.1% of the reported direct cost. This is a share of budget, not physical completion.')+rows([['Masonry',money(5592489)],['Conveying equipment',money(1120000)],['Specialties',money(72000)]]),source:'Portfolio pp. 8, 10. 33.1% calculated as finishes / reported direct cost.'},
 {title:'Testing and handover',phase:'07 / COMPLETE AND VERIFY',intro:'Test the systems, close defects, complete approvals and hand over the records needed to operate the terminal.',level:7,html:dates('Testing / handover: 21 Oct 2027–12 Jan 2028<br>Close-out row: 11–12 Jan 2028')+'<ol class="logic"><li>Integrated testing and final inspections</li><li>Punch-list correction and client walkover</li><li>As-built records, warranties and O&M manuals</li><li>Authority approval and project close-out</li></ol>'+note('The source names a critical sequence through site analysis, design, tender, procurement, excavation, foundations, structure, curtain wall, interiors and final fixtures. Any delay analysis requires the original P6 logic and calendars.')+note('Finish-date conflict: the overview says 24 Jan 2028, while the displayed schedule ends 12 Jan 2028.'),source:'Portfolio pp. 9–10. These are planned study dates, not evidence of completion.'}
 ];
 let index=0,timer=null;
 function show(i){index=Math.max(0,Math.min(chapters.length-1,i));const c=chapters[index];$('#chapter').textContent=`NEXUS TERMINAL / ${String(index+1).padStart(2,'0')}`;$('#title').textContent=c.title;$('#intro').textContent=c.intro;$('#content').innerHTML=c.html;$('#source').textContent=c.source;$('#phase-label').textContent=c.phase;$('#sequence').value=index;$('#counter').textContent=`${index+1} / ${chapters.length}`;$('#step-name').textContent=c.title.toUpperCase();$('#previous').disabled=index===0;$('#next').disabled=index===chapters.length-1;$('article').scrollTop=0;updateModel(c.level);if(index===chapters.length-1)stop();}
 function stop(){clearInterval(timer);timer=null;$('#play').textContent='Play sequence';$('#play').setAttribute('aria-pressed','false');}
 $('#next').onclick=()=>{stop();show(index+1);};$('#previous').onclick=()=>{stop();show(index-1);};$('#sequence').oninput=e=>{stop();show(Number(e.target.value));};
 $('#play').onclick=()=>{if(timer){stop();return;}if(index===chapters.length-1)show(0);timer=setInterval(()=>show(index+1),10000);$('#play').textContent='Pause sequence';$('#play').setAttribute('aria-pressed','true');};
 $('#sources').onclick=()=>{stop();$('#source-dialog').showModal();};$('#close-sources').onclick=()=>$('#source-dialog').close();
 $('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{});};
 document.addEventListener('keydown',e=>{if($('#source-dialog').open||['CANVAS','INPUT','BUTTON'].includes(e.target.tagName))return;if(e.key==='ArrowRight'){stop();show(index+1);}if(e.key==='ArrowLeft'){stop();show(index-1);}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
 let updateModel=()=>{};
 const canvas=$('#model');let renderer;
 try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});}catch(e){$('#fallback').hidden=false;canvas.hidden=true;$('.camera').hidden=true;show(0);return;}
 const T=THREE,scene=new T.Scene(),camera=new T.OrthographicCamera(-12,12,10,-10,.1,200),parts=[];
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.shadowMap.enabled=true;
 scene.add(new T.HemisphereLight(0xffffff,0x768867,2.4));const light=new T.DirectionalLight(0xfff7e4,2.8);light.position.set(-10,24,15);scene.add(light);
 const materials={concrete:new T.MeshStandardMaterial({color:0xdedfd3}),steel:new T.MeshStandardMaterial({color:0x8a9b8c}),glass:new T.MeshStandardMaterial({color:0x709493,transparent:true,opacity:.67}),earth:new T.MeshStandardMaterial({color:0x998775}),site:new T.MeshStandardMaterial({color:0xb5c29f}),gold:new T.MeshStandardMaterial({color:0xb9aa6a}),duct:new T.MeshStandardMaterial({color:0x748ca4}),pipe:new T.MeshStandardMaterial({color:0xb88462})};
 function box(w,h,d,m,x,y,z,phase){const obj=new T.Mesh(new T.BoxGeometry(w,h,d),materials[m].clone());obj.position.set(x,y,z);obj.castShadow=true;obj.receiveShadow=true;scene.add(obj);if(phase!==undefined)parts.push({obj,phase,original:obj.material.clone()});return obj;}
 function beam(a,b,r,m,phase){const v1=new T.Vector3(...a),v2=new T.Vector3(...b),o=new T.Mesh(new T.CylinderGeometry(r,r,v1.distanceTo(v2),6),materials[m].clone());o.position.copy(v1).add(v2).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v2.sub(v1).normalize());scene.add(o);parts.push({obj:o,phase,original:o.material.clone()});}
 box(18,.25,11,'site',0,-2.6,0);box(13,.2,6,'earth',0,-2.38,0,1);
 for(let x=-5;x<=5;x+=2.5)for(let z of [-1.7,1.7]){beam([x,-2.3,z],[x,-.4,z],.17,'concrete',1);box(.7,.3,.7,'concrete',x,-.4,z,1);}
 box(12,.35,4.8,'concrete',0,-.2,0,1);
 for(let l=0;l<3;l++){let y=l*1.8;for(let x=-5;x<=5;x+=2.5)for(let z of [-1.8,1.8])box(.23,1.65,.23,'concrete',x,y+.85,z,2);box(11.5,.2,4.4,'concrete',0,y+1.7,0,3);box(1,1.7,1.1,'concrete',3.8,y+.8,0,2);
 for(let side of [-1,1]){box(11.1,1.52,.045,'glass',0,y+.85,side*2.15,4);for(let x=-5.4;x<=5.4;x+=.65)box(.045,1.55,.065,'steel',x,y+.85,side*2.2,4);}
 box(10,.16,.33,'duct',0,y+1.42,-.7,5);beam([-5,y+1.38,.75],[5,y+1.38,.75],.055,'pipe',5);for(let x=-4;x<=4;x+=2)box(.18,.15,2.5,'duct',x,y+1.42,0,5);
 box(10.9,.04,4,'gold',0,y+.05,0,6);for(let x of [-3,0,3])box(1.2,.25,.4,'steel',x,y+.2,1.3,6);
 }
 for(let x=-5.5;x<=5.5;x+=1.1){beam([x,5.2,-2.3],[x,6.15,0],.05,'steel',4);beam([x,6.15,0],[x,5.2,2.3],.05,'steel',4);beam([x,5.2,-2.3],[x,5.2,2.3],.045,'steel',4);}
 box(11.9,.12,4.8,'concrete',0,6.3,0,4);
 for(let side of [-1,1])for(let i=0;i<24;i++)box(.2,.14+i*.07,.65,'concrete',-4.8+i*.2,i*.07,side*2.7,3);
 for(let x of [-7,7])for(let z of [-4,4]){beam([x,-2.2,z],[x,-1,z],.08,'steel',7);const tree=new T.Mesh(new T.IcosahedronGeometry(.6,1),materials.site);tree.position.set(x,-.7,z);scene.add(tree);parts.push({obj:tree,phase:7,original:tree.material.clone()});}
 const grid=new T.GridHelper(26,26,0x8b9b82,0xb5c3a6);grid.position.y=-2.76;scene.add(grid);
 let yaw=.65,pitch=.55,zoom=14,pan=false,target=new T.Vector3(0,1.3,0),drag=null;
 function render(){const el=$('.visual'),aspect=el.clientWidth/el.clientHeight;renderer.setSize(el.clientWidth,el.clientHeight,false);camera.left=-zoom*Math.max(1,aspect);camera.right=-camera.left;camera.top=zoom*Math.max(1,1/aspect);camera.bottom=-camera.top;camera.updateProjectionMatrix();camera.position.set(target.x+Math.sin(yaw)*Math.cos(pitch)*35,target.y+Math.sin(pitch)*35,target.z+Math.cos(yaw)*Math.cos(pitch)*35);camera.lookAt(target);renderer.render(scene,camera);canvas.dataset.stage=chapters[index].level;canvas.dataset.visible=parts.filter(p=>p.obj.visible).length;}
 updateModel=level=>{parts.forEach(({obj,phase,original})=>{obj.visible=phase<=level||level===0;obj.material.copy(original);obj.material.wireframe=level===0;if(level===0){obj.material.transparent=true;obj.material.opacity=.23;}if((level===5||level===6)&&phase===4){obj.material.transparent=true;obj.material.opacity=.1;obj.material.depthWrite=false;}else obj.material.depthWrite=true;if(phase===level&&level>0&&level<7)obj.material.emissive.set(0x18250b);});render();};
 function mode(value){pan=value;$('#pan').setAttribute('aria-pressed',String(value));$('#rotate').setAttribute('aria-pressed',String(!value));}$('#pan').onclick=()=>mode(true);$('#rotate').onclick=()=>mode(false);$('#zoom-in').onclick=()=>{zoom=Math.max(6,zoom-2);render();};$('#zoom-out').onclick=()=>{zoom=Math.min(25,zoom+2);render();};$('#reset').onclick=()=>{yaw=.65;pitch=.55;zoom=14;target.set(0,1.3,0);mode(false);render();};
 canvas.onpointerdown=e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag={x:e.clientX,y:e.clientY};if(pan){target.addScaledVector(new T.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),-dx*.03);target.y+=dy*.03;}else{yaw-=dx*.008;pitch=Math.max(.12,Math.min(1.4,pitch+dy*.005));}render();};for(const e of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(e,()=>drag=null);
 canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.15;if(e.key==='ArrowRight')yaw+=.15;if(e.key==='ArrowUp')pitch=Math.min(1.4,pitch+.1);if(e.key==='ArrowDown')pitch=Math.max(.12,pitch-.1);if(['+','='].includes(e.key))zoom=Math.max(6,zoom-1);if(e.key==='-')zoom=Math.min(25,zoom+1);render();};new ResizeObserver(render).observe($('.visual'));show(0);
})();
